// Help text for semibin2 single_easy_bin within CPIPES.

def semibin2sebHelp(params) {

    Map tool = [:]
    Map toolspecs = [:]
    tool.text = [:]
    tool.helpparams = [:]

    toolspecs = [
        'semibin2_single_easy_bin_run': [
            clihelp: 'Run SemiBin2 single_easy_bin tool. Default: ' +
                (params.semibin2_single_easy_bin_run ?: false),
            cliflag: null,
            clivalue: null
        ],
        'semibin2_seb_write_pre_reclustering_bins': [
            clihelp: 'Write pre-reclustering bins to disk. ' +
                "Default: ${params.semibin2_seb_write_pre_reclustering_bins}",
            cliflag: '--write-pre-reclustering-bins',
            clivalue: (params.semibin2_seb_write_pre_reclustering_bins ? ' ' : '')
        ],
        'semibin2_seb_no_write_pre_reclustering_bins': [
            clihelp: 'Do not write pre-reclustering bins to disk. ' +
                "Default: ${params.semibin2_seb_no_write_pre_reclustering_bins}",
            cliflag: '--no-write-pre-reclustering-bins',
            clivalue: (params.semibin2_seb_no_write_pre_reclustering_bins ? ' ' : '')
        ],
        'semibin2_seb_compression': [
            clihelp: 'Compression type for the output files ' +
                '(accepted values: gz [default]/xz/bz2/none). ' +
                "Default: ${params.semibin2_seb_compression}",
            cliflag: '--compression',
            clivalue: (params.semibin2_seb_compression ?: '')
        ],
        'semibin2_seb_orf_finder': [
            clihelp: 'ORF finder used to estimate the number of bins ' +
                '(fast-naive/prodigal/fraggenescan). ' +
                "Default: ${params.semibin2_seb_orf_finder}",
            cliflag: '--orf-finder',
            clivalue: (params.semibin2_seb_orf_finder ?: '')
        ],
        'semibin2_seb_depth_metabat2': [
            clihelp: 'Depth file generated by metabat2 (only used with single-sample binning). ' +
                "Default: ${params.semibin2_seb_depth_metabat2}",
            cliflag: '--depth-metabat2',
            clivalue: (params.semibin2_seb_depth_metabat2 ?: '')
        ],
        'semibin2_seb_environment': [
            clihelp: 'Environment for the built-in model ' +
                '(available choices: human_gut/dog_gut/ocean/soil/cat_gut/human_oral/mouse_gut/' +
                'pig_gut/built_environment/wastewater/chicken_caecum/global). ' +
                "Default: ${params.semibin2_seb_environment}",
            cliflag: '--environment',
            clivalue: (params.semibin2_seb_environment ?: '')
        ],
        'semibin2_seb_min_len': [
            clihelp: 'Minimal length for contigs in binning. ' +
                'If you use SemiBin with multi steps and you use this parameter, ' +
                'please use this parameter consistently with all subcommands. ' +
                '(Default: SemiBin chooses 1000bp or 2500bp according the ratio of the number of base pairs ' +
                'of contigs between 1000-2500bp). ' +
                "Default: ${params.semibin2_seb_min_len}",
            cliflag: '-m',
            clivalue: (params.semibin2_seb_min_len ?: '')
        ],
        'semibin2_seb_ratio': [
            clihelp: 'If the ratio of the number of base pairs of contigs between 1000-2500 bp smaller than this value, ' +
                'the minimal length will be set as 1000bp, otherwise 2500bp. ' +
                'Note that setting `--min-length/-m` overrules this parameter. ' +
                'If you use SemiBin with multi steps and you use this parameter, ' +
                'please use this parameter consistently with all subcommands. ' +
                '(Default: 0.05). ' +
                "Default: ${params.semibin2_seb_ratio}",
            cliflag: '--ratio',
            clivalue: (params.semibin2_seb_ratio ?: '')
        ],
        'semibin2_seb_cannot_name': [
            clihelp: 'Name for the cannot-link file (default: cannot). ' +
                "Default: ${params.semibin2_seb_cannot_name}",
            cliflag: '--cannot-name',
            clivalue: (params.semibin2_seb_cannot_name ?: '')
        ],
        'semibin2_seb_taxonomy_annotation_table': [
            clihelp: 'Pre-computed mmseqs2 format taxonomy TSV file to bypass mmseqs2 GTDB annotation [advanced]. ' +
                'When running with multi-sample binning, please make sure that the order of the taxonomy TSV file ' +
                'and the contig file (used for the combined fasta) is same. ' +
                "Default: ${params.semibin2_seb_taxonomy_annotation_table}",
            cliflag: '--taxonomy-annotation-table',
            clivalue: (params.semibin2_seb_taxonomy_annotation_table ? ' ' : '')
        ],
        'semibin2_seb_epochs': [
            clihelp: 'Number of epochs used in the training process (Default: 15). ' +
                "Default: ${params.semibin2_seb_epochs}",
            cliflag: '--epochs',
            clivalue: (params.semibin2_seb_epochs ?: '')
        ],
        'semibin2_seb_batch_size': [
            clihelp: 'Batch size used in the training process (Default: 2048). ' +
                "Default: ${params.semibin2_seb_batch_size}",
            cliflag: '--batch-size',
            clivalue: (params.semibin2_seb_batch_size ?: '')
        ],
        'semibin2_seb_minfasta_kbs': [
            clihelp: 'Minimum bin size in Kbps (Default: 200). ' +
                "Default: ${params.semibin2_seb_minfasta_kbs}",
            cliflag: '--minfasta-kbs',
            clivalue: (params.semibin2_seb_minfasta_kbs ?: '')
        ],
        'semibin2_seb_random_seed': [
            clihelp: 'Random seed. Set it to a fixed value to reproduce results across runs. ' +
                'The default is that the seed is set by the system. ' +
                "Default: ${params.semibin2_seb_random_seed}",
            cliflag: '--random-seed',
            clivalue: (params.semibin2_seb_random_seed ?: '')
        ],
        'semibin2_seb_ml_threshold': [
            clihelp: 'Length threshold for generating must-link constraints. ' +
                '(By default, the threshold is calculated from the contig, and the default minimum value is 4,000 bp). ' +
                "Default: ${params.semibin2_seb_ml_threshold}",
            cliflag: '--ml-threshold',
            clivalue: (params.semibin2_seb_ml_threshold ?: '')
        ],
        'semibin2_seb_engine': [
            clihelp: 'Device used to train the model ' +
                '(auto/gpu/cpu, auto means if SemiBin detects the gpu, SemiBin will use GPU). ' +
                "Default: ${params.semibin2_seb_engine}",
            cliflag: '--engine',
            clivalue: (params.semibin2_seb_engine ?: '')
        ],
        'semibin2_seb_semi_supervised': [
            clihelp: 'Train the model with semi-supervised learning. ' +
                "Default: ${params.semibin2_seb_semi_supervised}",
            cliflag: '--semi-supervised',
            clivalue: (params.semibin2_seb_semi_supervised ? ' ' : '')
        ],
        'semibin2_seb_self_supervised': [
            clihelp: 'Train the model with self-supervised learning. ' +
                "Default: ${params.semibin2_seb_self_supervised}",
            cliflag: '--self-supervised',
            clivalue: (params.semibin2_seb_self_supervised ? ' ' : '')
        ],
        'semibin2_seb_sequencing_type': [
            clihelp: 'Sequencing type in [short_read/long_read], Default: short_read. ' +
                "Default: ${params.semibin2_seb_sequencing_type}",
            cliflag: '--sequencing-type',
            clivalue: (params.semibin2_seb_sequencing_type ?: '')
        ],
        'semibin2_seb_max_edges': [
            clihelp: 'The maximum number of edges that can be connected to one contig (Default: 200). ' +
                "Default: ${params.semibin2_seb_max_edges}",
            cliflag: '--max-edges',
            clivalue: (params.semibin2_seb_max_edges ?: '')
        ],
        'semibin2_seb_max_node': [
            clihelp: 'Fraction of contigs that considered to be binned (should be between 0 and 1; default: 1). ' +
                "Default: ${params.semibin2_seb_max_node}",
            cliflag: '--max-node',
            clivalue: (params.semibin2_seb_max_node ?: '')
        ],
        'semibin2_seb_no_recluster': [
            clihelp: 'Do not recluster bins. ' +
                "Default: ${params.semibin2_seb_no_recluster}",
            cliflag: '--no-recluster',
            clivalue: (params.semibin2_seb_no_recluster ? ' ' : '')
        ]
    ]

    toolspecs.each {
        k, v -> tool.text['--' + k] = "${v.clihelp}"
        tool.helpparams[k] = [ cliflag: "${v.cliflag}", clivalue: v.clivalue ]
    }

    return tool
}